# Generated by Django 3.2.18 on 2023-05-02 11:31
# type: ignore
import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 2, 11, 31, 39, 878242)
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ac.transaction"
                    ),
                ),
            ],
        ),
    ]
