version: "3.9"
services:
  sales:
    image: sales
    depends_on:
      - sales_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - .:/app
  sales_db:
    image: postgres
    restart: always
    command: -p 5435
    env_file:
      - .env
    expose:
      - 5435
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
