apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-selector
  template:
    metadata:
      labels:
        app: sales-selector
    spec:
      containers:
        - name: sales-container
          image: sales-sales
          imagePullPolicy: Never
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4444
      targetPort: 8001
  selector:
    app: sales-selector
