apiVersion: apps/v1
kind: Deployment
metadata:
  name: wh-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wh-selector
  template:
    metadata:
      labels:
        app: wh-selector
    spec:
      containers:
        - name: wh-container
          image: warehouse-warehouse
          imagePullPolicy: Never
          ports:
            - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: wh-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5555
      targetPort: 8002
  selector:
    app: wh-selector
