name: build&push

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Warehouse
        id: wh_meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.WH_HUB_REPOSITORY }}

      - name: Build and push warehouse
        uses: docker/build-push-action@v4
        with:
          context: ./warehouse
          file: ./warehouse/Dockerfile
          push: true
          tags: ${{ steps.wh_meta.outputs.tags }}
          labels: ${{ steps.wh_meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Accounting
        id: ac_meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.AC_HUB_REPOSITORY }}

      - name: Build and push warehouse
        uses: docker/build-push-action@v4
        with:
          context: ./accounting
          file: ./accounting/Dockerfile
          push: true
          tags: ${{ steps.ac_meta.outputs.tags }}
          labels: ${{ steps.ac_meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Sales
        id: sls_meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.SLS_HUB_REPOSITORY }}

      - name: Build and push warehouse
        uses: docker/build-push-action@v4
        with:
          context: ./sales
          file: ./sales/Dockerfile
          push: true
          tags: ${{ steps.sls_meta.outputs.tags }}
          labels: ${{ steps.sls_meta.outputs.labels }}
